# config/config.yaml
paths:
  raw: data/raw
  bronze: data/bronze
  silver: data/silver
  gold: data/gold
  faiss_index: data/gold/faiss.index
  embeddings_npz: data/gold/embeddings.npz
  meta_parquet: data/gold/meta.parquet

spark:
  app_name: "LLM-Spark-RAG"
  master: "local[*]"
  partitions: 8

chunking:
  target_tokens: 300
  overlap_tokens: 50

embeddings:
  provider: "huggingface"   # or "huggingface"
  model: "sentence-transformers/all-MiniLM-L6-v2"  # e.g., OpenAI
  batch_size: 64

retrieval:
  top_k: 5

llm:
  provider: "openai"      # or "huggingface"
  model: "gpt-4o-mini"    # pick what you have access to
  max_tokens: 400
  temperature: 0.7